# Generated by Django 4.0.3 on 2022-03-16 02:48

import wagtail.core.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
